name: geconpy-dev
channels:
  - conda-forge
  - nvidia
  - nodefaults

dependencies:
  # Core dependencies
  - python=3.12
  - pymc>=5.27.1
  - pytensor>=2.37.0
  - matplotlib
  - numba
  - numpy
  - pandas
  - pyparsing
  - preliz>=0.23.0
  - scipy
  - setuptools
  - statsmodels
  - sympy>=1.14.0
  - sympytensor
  - pip
  - ipython
  - notebook<7
  - nutpie
  - networkx
  - sympytensor
  - pymc-extras>=0.8.0

  # For building docs
  - ipython
  - jupyter-sphinx
  - myst-nb
  - numpydoc
  - pre-commit
  - sphinx>=5
  - sphinx-copybutton
  - sphinx-design
  - sphinx-notfound-page
  - sphinx-sitemap
  - sphinx-codeautolink
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme
  - watermark

  # developer tools
  - pre-commit
  - pytest
  - pytest-env
  - pytest-cov
  - pandas-datareader

  - pip:
      - numdifftools
      - jax>0.9
      - corner
      - -e ../.
