name: geconpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core dependencies
  - python=3.12
  - pymc>=5.27.1
  - pytensor>=2.37.0
  - matplotlib
  - numba
  - numpy
  - pandas
  - pyparsing
  - scipy
  - setuptools
  - statsmodels
  - preliz>=0.23.0
  - sympy>=1.14.0
  - pymc-extras>=0.8.0
  - better-optimize
  - preliz
  - ipython
  - nutpie
  - networkx
  - sympytensor>=1.4.0
  - pymc-extras

  - pip:
      - jax>0.8
      - flowjax
