name: geconpy-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core dependencies
  - python=3.12
  - pip
  - pymc>=5.25.0
  - pytensor
  - joblib
  - matplotlib
  - numba
  - numpy
  - pandas
  - pyparsing
  - scipy
  - setuptools
  - statsmodels
  - preliz>=0.2.0
  - sympy>=1.14.0
  - pymc-extras
  - better-optimize
  - sympytensor
  - jax
  - nutpie

  # Extra dependencies for docs build
  - ipython
  - jupyter-sphinx
  - myst-nb
  - numpydoc
  - pre-commit
  - sphinx>=5
  - sphinx-copybutton
  - sphinx-design
  - sphinx-notfound-page
  - sphinx-sitemap
  - sphinx-codeautolink
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme
  - watermark
